[[questions]]
expected_sql = '''



-- Please write the SQL query that answer the question below
-- Then the column_names and different table_name that you used to write the query include them in the [[questions.expected_tables_columns.tables]] below




'''
id = 0
level = 'easy'
name = 'Distinct app users Reisverzekering'
question = 'How many distinct customers logged into the app and have a Doorlopende Reisverzekering in the last month?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [ 'COLUMN_NAME_1', 'COLUMN_NAME_2', 'COLUMN_NAME_3'... ]
    table_name = 'Table_name_1'

    [[questions.expected_tables_columns.tables]]
    column_names = [ 'COLUMN_NAME_1', 'COLUMN_NAME_2', 'COLUMN_NAME_3'... ]
    table_name = 'Table_name_2'

[[questions]]
expected_sql = '''







'''
id = 1
level = 'easy'
name = 'New mortgage users 2024'
question = 'How many new mortgage users do we have per month in 2024?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]
expected_sql = '''








'''
id = 2
level = 'easy'
name = 'App users segment 456'
question = 'How many regular app users are there for segment 456?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]
expected_sql = '''







'''
id = 3
level = 'easy'
name = 'nan'
question = 'How many investment customers do we have?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]
expected_sql = '''


 





'''
id = 4
level = 'nan'
name = 'nan'
question = 'How many new mortgage customers do we have in feb 2025 compared to feb 2024?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]
expected_sql = '''







'''
id = 5
level = 'nan'
name = 'nan'
question = 'How many customers logged in the app in the current month and Has a Doorlopende Reisverzekering per agecategory'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]
expected_sql = '''









'''
id = 6
level = 'nan'
name = 'nan'
question = 'How many Primary Mobile Customers do we have'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''






'''
id = 7
level = 'nan'
name = 'nan'
question = 'What is distribution of the channels of our Primary Mobile Customers?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [     ]
    table_name = 

[[questions]]

expected_sql = '''






'''
id = 8
level = 'nan'
name = 'nan'
question = 'How many customers withdrawn money from an ATM in the last 6 months?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''






'''
id = 9
level = 'nan'
name = 'nan'
question = 'How many times has a customer on average withdrawn money from an ATM in the last year?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]
expected_sql = '''






'''
id = 10
level = 'nan'
name = 'nan'
question = 'How many days has a customer visited an ATM in the last month?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]
expected_sql = '''






'''
id = 11
level = 'nan'
name = 'nan'
question = 'How many days has a customer visited an ATM in the last 3 months?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]
expected_sql = '''






'''
id = 12
level = 'nan'
name = 'nan'
question = 'How many days has a customer visited an ATM in the last 12 months?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]
expected_sql = '''






'''
id = 13
level = 'nan'
name = 'nan'
question = 'How often Private Banking customers visit an ATM compared to Mass customers?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''
    





'''
id = 14
level = 'nan'
name = 'nan'
question = 'What is the average frequency of ATM withdrawals per month in the last 12 months?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''






'''
id = 15
level = 'nan'
name = 'nan'
question = 'What is the difference for a unique customer identifier for business and retail customers?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''





'''
id = 16
level = 'nan'
name = 'nan'
question = 'What is the customer number with sequence number used for linking facts to the version of D_PARTY?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''






'''
id = 17
level = 'nan'
name = 'nan'
question = 'How is the customer age distribution among business customers?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''





'''
id = 18
level = 'nan'
name = 'nan'
question = 'Is there a primary digital customer with more than 1 login in the last 3 months on ING Web and App?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''






'''
id = 19
level = 'nan'
name = 'nan'
question = 'What is the source system of the data?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''





'''
id = 20
level = 'nan'
name = 'nan'
question = 'How many unique households do we have ?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''






'''
id = 21
level = 'nan'
name = 'nan'
question = 'What is the segment category with the most customers?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''






'''
id = 22
level = 'nan'
name = 'nan'
question = 'Has there a customer logged in on the ING banking app at least once in the past 3 months?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''





'''
id = 23
level = 'nan'
name = 'nan'
question = 'How many times customers log in on the ING app in 1 month?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''






'''
id = 24
level = 'nan'
name = 'nan'
question = 'How many customers logged in on the ING app or web with an Android phone in the last month?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name =

[[questions]]

expected_sql = '''





'''
id = 25
level = 'nan'
name = 'nan'
question = 'How many days have passed on average since the last login on the ING app for customers older than 50?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''





'''
id = 26
level = 'nan'
name = 'nan'
question = 'Has the relation logged in on the closed web environment at least once a week over the past 4 weeks?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''







'''
id = 27
level = 'nan'
name = 'nan'
question = 'What type of customers only use Web and not App ?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''




'''
id = 28
level = 'nan'
name = 'nan'
question = 'What is the median of how many days a customer logged in on the ING website in the last 12 months?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''





'''
id = 29
level = 'nan'
name = 'nan'
question = 'How many days have passed since the last login on the ING website by a business customer?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''




'''
id = 30
level = 'nan'
name = 'nan'
question = 'How many times has a customer logged in on the ING app or web in the last 1 month?'
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

[[questions]]

expected_sql = '''





'''
id = 31
level = 'nan'
name = 'nan'
question = "How many customer younger than 40 contacted ING by phone in the last 12 months?'"
type = 'nan'

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 

    [[questions.expected_tables_columns.tables]]
    column_names = [  ]
    table_name = 