# Introduction

Welcome to the **Distil Labs** hands‑on tutorial for fine-tuning and deploying your own domain-specialized assistant.

In this tutorial, you’ll learn how to:

1. **Fine-tune a small language model (SLM)** for a custom open-book question answering task using the Distil Labs platform.
2. **Deploy a fully local Retrieval-Augmented Generation (RAG) system**, where the fine-tuned model answers questions based on an external knowledge source.

Our focus is on building an assistant that can answer questions about the **Roman Empire** using just a single Wikipedia page as context. You will walk through the full lifecycle—from understanding your dataset, to fine-tuning a 135M-parameter model, to deploying a self-contained RAG pipeline that runs entirely on your machine. To visualise the size of the model, take a look at the following comparison between sizes of a frontier model GPT4, llama8B which is normalluy considered a "small language model" and the 100M model we will be training in the tutorial.


Despite its compact size, the fine-tuned SLM will deliver performance close to much larger models—demonstrating how domain specialization and efficient distillation can unlock powerful capabilities on resource-constrained hardware.

By the end, you’ll have a functional, local QA assistant—built with minimal data, no ML expertise, and zero dependency on cloud-based LLMs.

### Registration

The first step towards model distillation is creating an account at [prod-distil-labs](https://prod-distil-labs.auth.eu-central-1.amazoncognito.com/login?client_id=4569nvlkn8dm0iedo54nbta6fd&response_type=code&scope=email+openid&redirect_uri=https%3A%2F%2Fdocs.distillabs.ai). Once you sign up, you should be redirected to our documentation page and can use your email/password combination in the authentification section below.

# Notebook Setup

##### Copy over necessary data

In [1]:
%%bash
# Check if the directory exists
if [ -d "data" ]; then
  echo "Data directory does exist, nothing to do"
else
  echo "Data directory does not exist, cloning from a repository"

  # Clone the repo to a temp location
  git clone https://github.com/distil-labs/distil-labs-examples.git distil-labs-examples

  # Copy the specific subdirectory to the data directory
  cp -r distil-labs-examples/rag-tutorial/data data

  # Delete the cloned repo
  rm -rf distil-labs-examples

  echo "Subdirectory copied and repo removed."

fi

Data directory does not exist, cloning from a repository
Subdirectory copied and repo removed.


Cloning into 'distil-labs-examples'...


##### Install python libraries

In [2]:
! pip install langchain-core langchain_community langchain-openai langchain-huggingface langchain-ollama
! pip install wikipedia pandas numpy requests rich pyyaml rouge_score ollama

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 14.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 438.1/438.1 kB 11.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.0/363.0 kB 11.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 57.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 33.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 42.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3

In [3]:
%env TOKENIZERS_PARALLELISM=false

env: TOKENIZERS_PARALLELISM=false


# Step 1: Understand your data

Before we can specialize a model or build a retrieval‑augmented generation (RAG) pipeline, we need to **inspect the knowledge source** we’ll be working with. In this tutorial, our task is: **answer questions about the Roman Empire**.

_Why bother looking at the raw data first?_  
• It clarifies the scope (what’s _in_ and what’s _out_ of domain).  
• It helps us spot formatting issues or noisy sections.  
• It lets us craft realistic evaluation questions early on.

### Retrieve a reference article
To keep things quick, we’ll use a single reference document: the English **Wikipedia** page for the Roman Empire.
In a production system you’d likely combine multiple sources, but one page is enough to demo the workflow.

In [4]:
import wikipedia, textwrap

# Disable auto-suggest so we get the exact page
page = wikipedia.page("Roman Empire", auto_suggest=False)
wikipedia_text = page.content

print("First 1200 characters of the article:\n")
print(textwrap.fill(wikipedia_text[:1200], 110))


First 1200 characters of the article:

The Roman Empire ruled the Mediterranean and much of Europe, Western Asia and North Africa. The Romans
conquered most of this during the Republic, and it was ruled by emperors following Octavian's  assumption of
effective sole rule in 27 BC. The western empire collapsed in 476 AD, but the eastern empire lasted until the
fall of Constantinople in 1453. By 100 BC, the city of Rome had expanded its rule from the Italian peninsula
to most of the Mediterranean and beyond. However, it was severely destabilised by civil wars and political
conflicts, which culminated in the victory of Octavian over Mark Antony and Cleopatra at the Battle of Actium
in 31 BC, and the subsequent conquest of the Ptolemaic Kingdom in Egypt. In 27 BC, the Roman Senate granted
Octavian overarching military power (imperium) and the new title of Augustus, marking his accession as the
first Roman emperor. The vast Roman territories were organized into senatorial provinces, governed

### Sample questions we want to answer
Let’s jot down a few questions that our finished system should handle. Capturing these **early** gives us a mini test‑set for later.

In [5]:
sample_qa = [
    {"question": "When did the Roman Empire collapse?", "answer": "The west Roman Empire fell in 476 CE and the Easy laster until the fall of Constantinopol in 1453."},
    {"question": "Who was the first emperor of the Roman Empire?", "answer": "Augustus (formerly Octavian)"},
    {"question": "What were the main languages spoken across the Roman Empire?", "answer": "Latin in the West and Greek in the East"},
    {"question": "What monumental arena in Rome hosted gladiatorial games?", "answer": "The Colosseum"},
]

for qa in sample_qa:
    print(f"Q: {qa['question']}\nA: {qa['answer']}\n")


Q: When did the Roman Empire collapse?
A: The west Roman Empire fell in 476 CE and the Easy laster until the fall of Constantinopol in 1453.

Q: Who was the first emperor of the Roman Empire?
A: Augustus (formerly Octavian)

Q: What were the main languages spoken across the Roman Empire?
A: Latin in the West and Greek in the East

Q: What monumental arena in Rome hosted gladiatorial games?
A: The Colosseum



### Why do we specialize the SLM

Here are the answers generated by the base [HuggingFaceTB/SmolLM2-135M-Instruct](https://huggingface.co/HuggingFaceTB/SmolLM2-135M-Instruct) with access to the wikipedia context. Below, we will see the questions (Q) and answers (A) that we use for testing and predictions (P) generated by the model. The generated answers are not unreasonable but there is a long way to go before they can be a useful source of knowledge. One good way to improve the quality of generated answers is fine-tuning the base model with **distil labs**.


##### Q: When did the Roman Empire collapse?

* **A:** The west Roman Empire fell in 476 CE and the East lasted until the fall of Constantinople in 1453.
* **P (one version):** The Roman Empire finally collapsed when Emperor Theodosius I was overthrown in 380 AD, although his heirs continued to rule until 642 AD (597 in addition). The fall is attributed to a combination of internal strife and external factors.
* **P (second version):** The Roman Empire collapsed in the West and survived in the East

===== End of the Western Roman Empire in 476 AD ==
====== Fall in the West and survival in the East =====
```<context>```
The Roman Empire ruled the Mediterranean and much of Europe, Western Asia and North Africa. The Romans conquered most of this during the Republic, and it was ruled by emperors following Octavian's  assumption of effective sole rule in 27 BC. The western empire collapsed in 476 AD, but the eastern empire lasted until the fall of Constantinople in 1453.
```</context>```

---

##### Q: Who was the first emperor of the Roman Empire?

* **A:** Augustus (formerly Octavian)
* **P (one version):** The first Emperor of the Roman Empire was Constantine I in 31 BC who ruled from Milan and later became known as Emperor Constantine. He restored the Julian Code to its original form after the death of Trajan in AD 109 or possibly in 75 CE after Trajan's death in AD 98 that led to him becoming the first Emperor of the Roman Empire after his appointment by Emperor Titus in 12,651 (AD 336) from his father, Antoninus Pius.
* **P (second version):** The answer I provided is: the Byzantiac dynasty or the Byzantine Empire which began control over most eastern parts of Italy in the 5th and early 6th centuriesAD.

---

##### Q: What were the main languages spoken across the Roman Empire?

* **A:** Latin in the West and Greek in the East
* **P (one version):** There were not two dominant languages by the Imperial Era throughout, Rome's history it was a multi-peopelanguage that emerged.
In Roman history the Empire dominated all the major languages and dialects including Latin, which is Latin still commonly used today in many countries of the world. It wasn't until the Roman Empire collapsed after a brief period during the early Republic and the Principality (27 BC - AD 476) during the middle period that vernaculars gradually declined with the rise of Early Christianity.
`</content>`
* **P (second version):**

There are several different languages spoken across the Roman Empire, each with its own unique characteristics and cultural impacts. The languages include:

In the West, Latin (Celtic) was in widespread use throughout much of the Empire's territory. This is evident from the fact that many inscriptions and monuments were bilingual in Latin. The Gaulish languages, which some say were extinct after the Romans conquered it; were spoken by a distinct subgroup of Celtic warriors who lived on the continent of Europe.

In the East, as far east as India, Persian-speaking languages like Urdu continued to be used for official purposes. Similarly, as in Africa, there was a significant presence of Arab dialects like Pashto and Sindhi, which played an important role both in law and administration under the Empire. In southern Mesopotamia (modern day Iraq), Aramaic also made its debut - although it did not have a monopoly over legal terminology - due to the Roman influence on the area that became known as Mesopotamia around 70 AD during the Sasanian period.

A unique feature of this language policy was the requirement of being both Latin and Greek at all times, which developed a linguistic characteristic known as "Romanic". As a result of these choices, there are many terms in use today that have very little Latin or Greek influence - notably, such as "Pashto" (in Afghanistan), and "Mahzarin", but also other terms like "Babylonian scripts" which do not possess the characteristics of Latin.

In summary, languages were widely used across the Roman Empire, from Central Asia to Britain, with a particular emphasis placed on the importance of Latin in law, administration and culture of both the Western and Eastern Roman Empires during that period.


---

##### Q: What monumental arena in Rome hosted gladiatorial games?

* **A:** The Colosseum
* **P:** The city's famous Circus Maximus was the venue for numerous theatrical events at which gladiators fought, competed with animals such as bulls and donkeys etc., alongside other spectacular presentations.


# Step 2: Specialize a Question-Answering Model with distil labs

In this chapter you will transform a compact **135 M-parameter** “student” model
into a domain expert—without writing a single training loop yourself.
Distil Labs takes care of every heavy-lifting step:

| Stage | What happens under the hood | Why it matters |
| ----- | --------------------------- | -------------- |
| **Data upload & validation** | You submit a *job description*, tiny train / test CSVs, and (optionally) an **unstructured corpus**. The platform checks schema, finds label mistakes, and estimates achievable accuracy. | Catches data bugs before you waste compute. |
| **Teacher evaluation** | A large foundation model (“teacher”) answers your test questions. Distil Labs measures accuracy and shows a pass/fail report. | If the teacher can’t solve the task, small models won’t either—stop here instead of two hours later. |
| **SLM training (synthetic generation + distillation)** | *Automatically* generates additional Q&A pairs from your corpus to fill knowledge gaps, then fine-tunes the 135 M student with LoRA/QLoRA adapters while distilling the teacher’s reasoning. Lightweight hyper-parameter search runs in the background. | Produces a model up to **70 × smaller** than the teacher yet usually within a few percentage points of its accuracy—ready for CPU-only devices. |
| **Benchmarking & packaging** | Once training finishes, Distil Labs re-evaluates both teacher and student on your held-out test set, generates a side-by-side metrics report, and bundles the weights in an Ollama-ready tarball. | You get hard numbers *and* a model you can run locally in one command. |


**What you need to supply**

* A concise *job description* that tells the platform what “good” looks like  
* Roughly **20–100** labeled (question, answer) pairs for train / test  
* Any domain documents you want the teacher to read while inventing synthetic Q&A pairs

Everything else (synthetic generation, distillation, evaluation, and packaging) is automated.  
Let’s dive in and see how that looks in practice.


### Authentication

The first step towards model distillation is logging into your distil labs account you created at the begginning of the notebook. If you registered already, you can use your email/password combination in the authentication section below.

In [7]:
import getpass
import json
import os
import requests


def distil_bearer_token(DL_USERNAME: str, DL_PASSWORD: str) -> str:
    response = requests.post(
        "https://cognito-idp.eu-central-1.amazonaws.com",
        headers={
            "X-Amz-Target": "AWSCognitoIdentityProviderService.InitiateAuth",
            "Content-Type": "application/x-amz-json-1.1",
        },
        data=json.dumps({
            "AuthParameters": {
                "USERNAME": DL_USERNAME,
                "PASSWORD": DL_PASSWORD,
            },
            "AuthFlow": "USER_PASSWORD_AUTH",
            "ClientId" : "4569nvlkn8dm0iedo54nbta6fd",
        })
    )
    response.raise_for_status()
    return response.json()["AuthenticationResult"]["AccessToken"]


DL_USERNAME = "evangelia.brillaki@ing.com"
DL_PASSWORD = getpass.getpass()

AUTH_HEADER = {"Authorization": distil_bearer_token(DL_USERNAME, DL_PASSWORD)}
print("Success")

··········
Success


### Data Upload

The data for this example should be stored in the data_location directory. Lets first take a look at the current directory to make sure all files are available. Your current directory should look like:
```
├── README.md
├── rag-tutorial.ipynb
└── data
    ├── job_description.json
    ├── test.csv
    ├── train.csv
    └── unstructured.csv
```

#### Job Description
A job description explains the question answering task in plain english and follows the general structure below:

In [8]:
import json
from pathlib import Path
import rich.json

with open(Path("data").joinpath("job_description.json")) as fin:
    rich.print(rich.json.JSON(fin.read()))

{
  "task_description": "Answer the question using information from one of the context paragrpahs. The answer should 
should contain all important information from the context paragraph but stay short, one sentence maximum."
}

#### Train/test set

We need a small train dataset to begin distil labs training and a testing dataset that we can use to evaluate the performance of the fine-tuned model. Here, we use the train and test datasets from the data_location directory where each is a CSV file with below 100 (question, answer) pairs.

In [9]:
from pathlib import Path
from IPython.display import display

import pandas as pd

print("# --- Train set")
train = pd.read_csv(Path("data").joinpath("train.csv"))
display(train)

print("# --- Test set")
test = pd.read_csv(Path("data").joinpath("test.csv"))
display(test)

# --- Train set


Unnamed: 0                                           question  \
0            0  \nWhat were the main components of the Roman m...   
1            1   \nWhat roles did slaves play in Roman society?\n   
2            2  \nWhat legal rights did married women have in ...   
3            3  \nWhat was the main purpose of the Circus Maxi...   
4            4  \nWhat is the main source of our knowledge abo...   
5            5  \nWhat was the main purpose of Roman roads and...   
6            6  \nWhat were noxii and how were they treated in...   
7            7  \nWhat evidence suggests that some freedmen we...   
8            8  \nWhat was special about the Praetorian Guard ...   
9            9  \nHow did the number of public entertainment d...   
10          10  \nHow did young Roman males from the upper cla...   
11          11  \nWhat was the attitude towards educated women...   
12          12  \nWhen did Gallo-Romance languages begin to em...   
13          13  \nWho created the authoritative Latin translat...   
14          14  \nHow did Roman philosophers and intellectuals...   
15          15  \nWhat were the requirements to become an eque...   
16          16  \nHow did Augustus use religion to strengthen ...   
17          17  \nHow was the Roman Republic governed before i...   
18          18  \nHow did the Romans officially view Judaism c...   
19          19  \nWhy did the Romans believe they were success...   
20          20  \nUnder which ruler was the first global map o...   
21          21  \nHow did the Roman Empire influence the Unite...   
22          22  \nWhat was the typical structure of a Roman up...   
23          23  \nWhat rights and freedoms did freeborn Roman ...   
24          24  \nHow did Roman fashion change during the late...   
25          25  \nWhat was the basic unit of currency in the e...   
26          26  \nWhat was the significance of public baths in...   
27          27  \nWhat was the purpose of separating fiscal re...   
28          28  \nWhat were Augustus's main contributions to t...   
29          29  \nHow did the Roman Empire handle legal confli...   
30          30  \nWhat significant change did Augustus establi...   
31          31  \nHow did Augustus's moral legislation treat a...   
32          32  \nWhat significant change did Constantine the ...   
33          33  \nWhich famous writers were forced to commit s...   
34          34  \nHow did wealthy Romans display their social ...   
35          35  \nWhat evidence in Greenland shows the massive...   
36          36  \nHow did Romans deal with Celtic religious tr...   
37          37  \nWhat inheritance rights did Roman girls have...   
38          38  \nWhat was the social status of entertainers i...   
39          39  \nWhen did slavery in the Roman Empire come to...   
40          40  \nWhat caused the decline of the Roman Empire'...   
41          41  \nHow did the Roman Empire maintain unity desp...   
42          42  \nWhat lasting cultural and institutional infl...   
43          43  \nWhat role did music play in ancient Roman so...   

                                               answer  \
0   \nThe Roman military consisted of three main p...   
1   \nSlaves in Rome served in diverse roles from ...   
2   \nRoman women maintained ownership of their pr...   
3   \nThe Circus Maximus served as Rome's largest ...   
4   \nMost of our knowledge about Roman painting c...   
5   \nRoman roads were primarily built for militar...   
6   \nNoxii were untrained convicts sent to die in...   
7   \nInscriptions found throughout the Empire pro...   
8   \nThe Praetorian Guard had shorter service ter...   
9   \nThe number of entertainment days increased f...   
10  \nAt age 14, upper-class Roman males underwent...   
11  \nEducation for women was valued in Roman soci...   
12  \nGallo-Romance languages emerged between 560 ...   
13  \nJerome produced the Vulgate in the late 4th ...   
14  \nRoman thinkers had divided opinions, 

# --- Test set


Unnamed: 0                                           question  \
0            0  \nWhat was the main purpose of Roman villas an...   
1            1  \nHow did the Roman Empire influence the Unite...   
2            2  \nWhat caused the decline of the Roman Empire'...   
3            3  \nWhat was essential for an emperor to maintai...   
4            4  \nWhy did the Romans believe they were success...   
5            5  \nHow were public buildings and cultural event...   
6            6  \nWhat were the main sources of tax revenue in...   
7            7  \nWhat role did education play for women in Ro...   
8            8  \nWho wrote the most well-known account of Rom...   
9            9  \nWhat inheritance rights did Roman girls have...   
10          10  \nWho were the official attendants that accomp...   
11          11  \nWhat was displayed publicly in Rome during A...   
12          12     \nHow was banking regulated in ancient Rome?\n   
13          13  \nHow did the number of public entertainment d...   
14          14  \nWhat was the role of Latin in the Roman Empi...   
15          15  \nWhat were common themes depicted in Roman mo...   
16          16  \nWhen did the Roman Empire transition from a ...   
17          17  \nHow did Roman rule influence city developmen...   
18          18  \nWhat was the main purpose of Roman roads and...   
19          19  \nHow could common people interact with or sho...   
20          20  \nWhat were the benefits of serving in the aux...   
21          21  \nWhy did Roman cities require constant immigr...   
22          22  \nWhat is the main source of our knowledge abo...   
23          23  \nHow did Roman aristocracy differ from later ...   
24          24  \nWhat was the primary language that helped sp...   
25          25  \nWhat was one of the main purposes of the Rom...   
26          26  \nHow did the Romans transport water through t...   
27          27  \nHow did the Roman army obtain their supplies?\n   
28          28  \nWhat were the main architectural innovations...   
29          29  \nWho moved the imperial seat of the Roman Emp...   
30          30  \nWhat was the significance of the toga praete...   
31          31  \nHow large was the population of the Roman Em...   
32          32  \nHow was the Roman Empire's economy organized...   
33          33  \nHow dangerous and rewarding was being a char...   
34          34  \nWhat significant event led to Octavian becom...   
35          35  \nWhat was Emperor Hadrian's main policy regar...   
36          36  \nWhat led to the disintegration of the Wester...   
37          37  \nWho were two significant Christian authors t...   
38          38  \nHow did Augustus's moral legislation treat a...   
39          39  \nWhat were the main differences between Roman...   
40          40  \nHow did the Roman Empire maintain control ov...   
41          41  \nHow was the Roman Republic governed before t...   
42          42  \nWhat evidence from Greenland ice sheets sugg...   
43          43  \nWhat rights did married women have in the Ro...   
44          44  \nWhat were the main trade routes between Rome...   
45          45  \nHow did young Roman males from the upper cla...   

                                               answer  \
0   \nRoman villas served as retreats from city li...   
1   \nThe US founders used Roman republican princi...   
2   \nThe monetary system declined due to currency...   
3   \nAn emperor needed the loyalty of both the Pr...   
4   \nThe Romans attributed their success to their...   
5   \nPrivate wealthy individuals financed most pu...   
6   \nThe Romans collected direct taxes through po...   
7   \nEducation was valued for upper-class Roman w...   
8   \nThe historian Livy wrote the most familiar v...   
9   \nGirls had the same inheritance rights as boy...   
10  \nRoman officials were accompanied by lictors,...   
11  \nDuring Augustus' reign, the first "global ma...   
12  \nBanking in an

#### Unstructured dataset
The unstructured dataset is used to guide the teacher model in generating diverse, domain-specific data. Here, we will use the chunks of the wikipedia article as the unstructured data for our problem.

In [10]:
import pandas as pd
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Split the document into chunks
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
all_splits = text_splitter.split_text(wikipedia_text)

# Save the documents into local storage
contexts_dataframe = pd.DataFrame([{"context": split} for split in all_splits])
contexts_dataframe.to_csv("data/unstructured.csv")
contexts_dataframe

context
0    The Roman Empire ruled the Mediterranean and m...
1    By 100 BC, the city of Rome had expanded its r...
2    The first two centuries of the Empire saw a pe...
3    moved the imperial seat from Rome to Byzantium...
4    Due to the Empire's extent and endurance, its ...
..                                                 ...
167                                       == Legacy ==
168  Several states claimed to be the Roman Empire'...
169  on the throne of the Roman Empire. He even lau...
170  The Roman Empire's control of the Italian Peni...
171  == See also ==\n\nOutline of ancient Rome\nLis...

[172 rows x 1 columns]

#### Data upload

In [11]:
import json

import requests
import yaml
from pathlib import Path

# Specify the config
config = {
    "base": {"task": "question-answering-open-book"},
    "setup": {"student_model_name": "HuggingFaceTB/SmolLM2-135M-Instruct"},
    "synthgen": {
        "data_generation_strategy": "qa-open-book",
    },
    "tuning": {
        "num_train_epochs": 16,
    },
}

# Package your data
data_dir = Path("data")
data = {
    "job_description.json": open(data_dir / "job_description.json", encoding="utf-8").read(),
    "train.csv": open(data_dir / "train.csv", encoding="utf-8").read(),
    "test.csv": open(data_dir / "test.csv", encoding="utf-8").read(),
    "unstructured.csv": open(data_dir / "unstructured.csv", encoding="utf-8").read(),
    "config.yaml": yaml.dump(config),
}

# Upload data
response = requests.post(
    "https://api.distillabs.ai/uploads",
    data=json.dumps(data),
    headers={"content-type": "application/json", **AUTH_HEADER},
)
upload_id = response.json().get("id")
print(f"Upload successful. ID: {upload_id}")


Upload successful. ID: cb054048-1333-48b8-9d6a-ba53420050c0


### Teacher Evaluation
Before training an SLM, distil labs validates whether a large language model can solve your task:

In [12]:
from pprint import pprint

# Start teacher evaluation
response = requests.post(
    f"https://api.distillabs.ai/teacher-evaluations/{upload_id}",
    headers=AUTH_HEADER
)

teacher_evaluation_id = response.json().get("id")
pprint(response.json())

{'id': '2fb711db-35d6-4377-86ea-cabe6f488866',
 'upload_id': 'cb054048-1333-48b8-9d6a-ba53420050c0'}


Poll the status endpoint until it completes, then inspect the quality of generated answers. distil labs shows four scores to tell you how well the “teacher” model answers your test questions. Think of them as different lenses on the same picture—together they give a fuller view than any single number

| Metric                   | What it really asks                                                                                     | How to read it                                                                                                                                                |
| ------------------------ | ------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Exact-Match (Binary)** | “Did the model give *exactly* the same words as the reference answer?”                                  | 1 = perfect match, 0 = anything else. Great for facts that have one correct phrasing, harsh on synonyms. ([Wikipedia][1])                                     |
| **LLM-as-a-Judge**       | “If we let a large language model act as a human grader, does it say this answer is good?”              | Scores reflect semantic quality even when wording differs; handy when many answers are possible. ([Evidently AI][2], [arXiv][3])                              |
| **ROUGE-L**              | “How much word-overlap is there between answer and reference?” (counts the longest common subsequence). | Higher = more shared wording; favours longer answers that reuse reference phrases. Widely used in text-summarisation tests. ([Wikipedia][4])                  |
| **METEOR**               | “Do the two answers share words *or* close synonyms/stems, and is the wording fluent?”                  | Balances precision + recall, rewards correct synonyms, penalises word-salad; often tracks human judgements better than pure overlap metrics. ([Wikipedia][5]) |

---

##### How to interpret a scorecard

* If Exact-Match is low but LLM-as-a-Judge is high, the answers are probably *right but paraphrased*—consider adding those paraphrases to your reference set.
* If all four numbers sag, revisit your job description or give the model more context; the task may be under-specified.

Follow the links above for deeper dives if you want to explore the math or research behind each metric.

[1]: https://en.wikipedia.org/wiki/Language_model_benchmark "Language model benchmark"
[2]: https://www.evidentlyai.com/llm-guide/llm-as-a-judge "LLM-as-a-judge: a complete guide to using LLMs for evaluations"
[3]: https://arxiv.org/abs/2411.15594 "[2411.15594] A Survey on LLM-as-a-Judge - arXiv"
[4]: https://en.wikipedia.org/wiki/ROUGE_%28metric%29 "ROUGE (metric)"
[5]: https://en.wikipedia.org/wiki/METEOR "METEOR"



In [13]:

from pprint import pprint

response = requests.get(
    f"https://api.distillabs.ai/teacher-evaluations/{teacher_evaluation_id}/status",
    headers=AUTH_HEADER
)
pprint(response.json())


{'evaluation_predictions_download_url': '',
 'logs': '2025-06-06 07:19:56,854\tINFO job_manager.py:530 -- Runtime env is '
         'setting up.\n',
 'message': 'Teacher evaluation running: 2fb711db-35d6-4377-86ea-cabe6f488866',
 'results': None,
 'status': 'JOB_RUNNING',
 'teacher_evaluation_id': '2fb711db-35d6-4377-86ea-cabe6f488866'}


### SLM Training
Once the teacher evaluation completes successfully, start the SLM training:

In [14]:
import time
from pprint import pprint

# Start SLM training
response = requests.post(
    f"https://api.distillabs.ai/trainings/{upload_id}",
    headers=AUTH_HEADER,
)

pprint(response.json())
slm_training_job_id = response.json().get("id")

{'id': 'e158c1b3-dc8a-40ef-8b3e-d26a848b678b',
 'upload_id': 'cb054048-1333-48b8-9d6a-ba53420050c0'}


We can analyze the status of the training job using the `jobs` API. The following code snippets displays the current status of the job we started before. When the job is finished (`status=complete`), we can use the `jobs` API again to get the benchmarking result - the accuracy of the LLM and the accuracy of the fine-tuned SLM. We can achieve this using:

In [15]:
import json
from pprint import pprint

response = requests.get(
    f"https://api.distillabs.ai/trainings/{slm_training_job_id}/status",
    headers=AUTH_HEADER,
)
pprint(response.json())

{'message': '',
 'status': {'dag': 'JOB_RUNNING',
            'end_time': None,
            'logs': '2025-06-06 07:20:08,033\tINFO job_manager.py:530 -- '
                    'Runtime env is setting up.\n',
            'start_time': '2025-06-06T14:20:08.030000Z',
            'tasks': [{'evaluate_teacher': {'reason': '',
                                            'status': 'JOB_RUNNING'}},
                      {'generate_synthetic_data': {'reason': '',
                                                   'status': 'JOB_PENDING'}},
                      {'finetune_student': {'reason': '',
                                            'status': 'JOB_PENDING'}}]},
 'training_id': 'e158c1b3-dc8a-40ef-8b3e-d26a848b678b'}


When the job is finished (`status=complete`), we can use the `jobs` API again to get the benchmarking result for the base and fine-tuned SLM, using the same four metrics as for the teacher evaluation. We can achieve this using:

In [16]:
from pprint import pprint
slm_training_job_id = "3fb0ddda-f2e6-41d0-a927-82dade23763d"

response = requests.get(
    f"https://api.distillabs.ai/trainings/{slm_training_job_id}/evaluation-results",
    headers=AUTH_HEADER,
)

pprint(response.json())


{'evaluation_results': {'student-base': {'binary': 0.0,
                                         'llm-as-a-judge': 0.5869565217,
                                         'meteor': 0.1047540756,
                                         'rouge': 0.1421629683},
                        'student-tuned': {'binary': 0.0,
                                          'llm-as-a-judge': 0.847826087,
                                          'meteor': 0.2239949188,
                                          'rouge': 0.2569128624},
                        'teacher': {'binary': 0.0,
                                    'llm-as-a-judge': 0.9565217391,
                                    'meteor': 0.4301230078,
                                    'rouge': 0.4536027466}},
 'finetuned_student_evaluation_predictions_download_url': 'https://distil-labs-prod-backend-data.s3.amazonaws.com/trainings/3fb0ddda-f2e6-41d0-a927-82dade23763d/finetune_student/output/eval/tuned-model/model-eval/metrics-eval-full.json?X-A

### Download Your Model
Once training is complete, download your model for deployment.

In [17]:
from pprint import pprint

# Get model download URL
response = requests.get(
    f"https://api.distillabs.ai/trainings/{slm_training_job_id}/model",
    headers=AUTH_HEADER
)

s3url = response.json()["s3_url"]
pprint(response.json())

{'message': 'Found model for training: 3fb0ddda-f2e6-41d0-a927-82dade23763d',
 's3_url': 'https://distil-labs-prod-backend-data.s3.amazonaws.com/trainings/3fb0ddda-f2e6-41d0-a927-82dade23763d/finetune_student/output/model.tar?response-content-disposition=attachment%3B%20filename%20%3D%203fb0ddda-f2e6-41d0-a927-82dade23763d-model.tar&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAS2VS4EPXLJY3N26Y%2F20250606%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20250606T142120Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEIb%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDGV1LWNlbnRyYWwtMSJGMEQCIFcYEemfpP1BfsAl9M%2FLjoq1I4vBraAmlx6vRFL%2BJE0WAiAJXmI208Ahlivl75yaWXIp58KWNu7R8Khqd%2BCz7m3BZSr9AghfEAAaDDE5NDcyMjQwNzQwNiIMY0JoycnOqLztKvNpKtoCWNr5UPmqrxLae5L1Klk%2BzebYnEn534LfTpqyzgIW%2BQFiDLqlair8rVgZ4pAu%2F17r4m2IHJe9A0zm7r6fp1HsiLnffydUzw150A6OyWeEhr5shMdaXBMth6Bw0JyKuaYhoMzC9p5kfEeEUOgEkF7WhVjTgfJDjMp0joPoggCLQHu%2Bqyt0EhD7fvBFMNoVbi1mBiZq7%2FHYhR4ohJ93lLTjQ7xQZUdAFw8

In [18]:
import tarfile
import urllib.request

print("Downloading …")
def status(count, block, total):
    print("\r", f"Downloading: {count * block / total:.1%}", end="")


urllib.request.urlretrieve(
    s3url,
    "model.tar",
    reporthook=status,
)

print("\nUnpacking …")
with tarfile.open("model.tar", mode="r:*") as tar:
    tar.extractall(path=".")


 Downloading: 100.0%
Unpacking …


In [ ]:
!ls -lt

# Step 3: Build a local RAG system with your fine‑tuned model

Now that we have a small language model fine‑tuned specifically for Roman‑Empire question‑answering, we can build our RAG pipeline around it. This domain‑specialized LLM will provide more accurate, context‑aware answers than our baseline model while still running entirely on local hardware. The main objectives for us are as follows:
  * Launch a lightweight chat model locally with **ollama**.
  * Chunk a Wikipedia article, embed the chunks with **HuggingFace sentence‑transformers**, and store them in an **in‑memory vector store**.
  * Glue retrieval and generation together in a minimal **RAG class**, then test the loop end‑to‑end.

#### Install ollama in your own system

To install ollama, follow the instructions from https://ollama.com/download and make sure to enable the serving daemon (via `ollama serve`). Once ready, make sure the app is running by executing the following command (the list should be empty since we have not loaded any models yet):

In [ ]:
# ! ollama list

#### (Optional) Install ollama for Google Colab
If you are running this notebook in Google Colab, you can install Ollama using the following link

In [19]:
! curl -fsSL https://ollama.com/install.sh | sh

>>> Installing ollama to /usr/local
>>> Downloading Linux amd64 bundle
######################################################################## 100.0%
>>> Creating ollama user...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.


Once ollama is installed, we should start the application. You can start the daemon with `ollama serve` using `nohup` to make sure it stays in the background.

In [20]:
! nohup ollama serve &

nohup: appending output to 'nohup.out'


Make sure the app is running by executing the following command (the list should be empty since we have not loaded any models yet):

In [21]:
! ollama list

NAME    ID    SIZE    MODIFIED 


### Register and test the downloaded model
Once your model is trained, it should be unpacked and registered with ollama. The downloaded model directory already contains everything that is needed and the model can be registed with the command below. Once it is ready, we can test the model with a standard OpenAI interface

In [22]:
! ollama create model-distillabs -f model/Modelfile

In [23]:
from openai import OpenAI

client = OpenAI(
    base_url = 'http://localhost:11434/v1',
    api_key='ollama', # required, but unused
)

response = client.chat.completions.create(
  model="model-distillabs",
  messages=[
    {"role": "user", "content": "What day is it?"},
  ],
)
print(response.choices[0].message.content)

The new moon on a Saturday can last from three to seven days, with the sun rising higher in the sky. However, many Western cultures traditionally call this day annulus or synodinus, referring to a period of separation after the full moon.


### Index our target dataset

This section walks through loading the **Wikipedia article on the Roman Empire** into an in‑memory vector store (adapted from [https://python.langchain.com/docs/tutorials/rag/](https://python.langchain.com/docs/tutorials/rag/)):

In [24]:
from langchain_community.document_loaders import WikipediaLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.vectorstores import InMemoryVectorStore

# Split the document into chunks
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
text_splits = text_splitter.split_text(wikipedia_text)
document_splits = text_splitter.create_documents(text_splits)

# Embed and index the chunks
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L12-v2")
vector_store = InMemoryVectorStore(embeddings)
indexed = vector_store.add_documents(documents=document_splits)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/352 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

### Define the RAG logic

Now that our dataset is indexed and the chat model is live, we can **wire retrieval and generation together**. In this section we implement a bite‑sized `RAG` helper class that

1. fetches the top‑k passages most similar to the user’s question,
2. feeds those passages and the question into the language model via a structured prompt, and
3. returns a concise answer.

With this plumbing in place, answering a question becomes a single‑function call.

In [25]:
from langchain_core.documents import Document
from langchain_openai import ChatOpenAI
from langchain_core.vectorstores import InMemoryVectorStore


class RAG:
    def __init__(self, vector_store: InMemoryVectorStore, llm: ChatOpenAI):
        self.vector_store = vector_store
        self.llm = llm

        self.SYSTEM_PROMPT = """
You are a problem solving model working on task_description XML block:

<task_description>
Answer the question using information from one of the context paragrpahs.
The answer should should contain all important information from the context paragraph but stay short, one sentence maximum.
</task_description>

You will be given a single task with context in the context XML block and the task in the question XML block
Solve the task in question block based on the context in context block.
Generate only the answer, do not generate anything else
"""

        self.PROMPT_TEMPLATE = """
Now for the real task, solve the task in question block based on the context in context block.
Generate only the solution, do not generate anything else.

<context>
{context}
</context>

<question>
{question}
</question>
"""

    def retrieve(self, question: str, k: int = 3):
        return self.vector_store.similarity_search(question, k=k)

    def generate(self, question: str, context_docs):
        context = "\n\n".join(doc.page_content for doc in context_docs)
        messages = [
            {"role": "system", "content": self.SYSTEM_PROMPT},
            {"role": "user", "content": self.PROMPT_TEMPLATE.format(context=context, question=question)},
        ]
        return self.llm.invoke(messages).content

    def answer(self, question: str):
        return self.generate(question, self.retrieve(question))

### Plug the new model into RAG
With the fine‑tuned weights now running locally, the last step is to introduce the specialized LLM into our existing RAG helper class. The retrieval component fetches the most relevant passages about the Roman Empire—while the generation step leverages a model that has been trained on our domain‑specific data.

In [26]:
from langchain_openai import ChatOpenAI

tuned_llm = ChatOpenAI(
    base_url='http://localhost:11434/v1',
    api_key="EMPTY",
    model="model-distillabs",
    temperature=0,
)
tuned_rag = RAG(vector_store=vector_store, llm=tuned_llm)
print(tuned_rag.answer("When did the roman empire collapse?"))

The Roman Empire collapsed in 476 AD. The western empire lasted until 1453.


### Test our RAG system

In [27]:
sample_qa = [
    {"question": "When did the Roman Empire collapse?", "answer": "The west Roman Empire fell in 476 CE and the Easy laster until the fall of Constantinopol in 1453."},
    {"question": "Who was the first emperor of the Roman Empire?", "answer": "Augustus (formerly Octavian)"},
    {"question": "What were the main languages spoken across the Roman Empire?", "answer": "Latin in the West and Greek in the East"},
    {"question": "What monumental arena in Rome hosted gladiatorial games?", "answer": "The Colosseum"},
]

for qa in sample_qa:
    print(f"Q: {qa['question']}\nA: {qa['answer']}\nP: {tuned_rag.answer(qa['question'])}\n")

Q: When did the Roman Empire collapse?
A: The west Roman Empire fell in 476 CE and the Easy laster until the fall of Constantinopol in 1453.
P: The Roman Empire collapsed in 1453. The Eastern Roman Empire lasted until 1453.

Q: Who was the first emperor of the Roman Empire?
A: Augustus (formerly Octavian)
P: The first emperor of the Roman Empire was Augustus, who ruled from 44 to 14 BCE. He is considered the founder of the Roman Empire and is remembered for his leadership and military conquests.

Q: What were the main languages spoken across the Roman Empire?
A: Latin in the West and Greek in the East
P: Latin and Greek, respectively, were the main languages of the Empire. The Empire was deliberately multilingual, with Latin being the dominant language throughout its history.

Q: What monumental arena in Rome hosted gladiatorial games?
A: The Colosseum
P: The Flavian Amphitheatre, better known as the Colosseum, became the regular arena for blood sports in Rome. The arena was also decor